import type { Food } from "./types";

/* kcal & protein are per ONE unit; rows flagged `g` are per 100 g. */
const F = (n: string, e: string, u: string, k: number, p: number, g?: number, a?: string): Food =>
  ({ n, e, u, k, p, g: !!g, a: a || "" });

export const FOODS: Food[] = [
 /* tiffin & breads */
 F("Idli","🍚","idli",70,2,0,"tiffin breakfast"),
 F("Dosa (plain)","🫓","dosa",150,3,0,"tiffin"),
 F("Masala dosa","🫓","dosa",290,6),
 F("Rava dosa","🫓","dosa",160,3.5),
 F("Pesarattu","🫓","pesarattu",150,6,0,"moong dosa"),
 F("Uttapam","🫓","uttapam",180,5),
 F("Appam","🫓","appam",120,2),
 F("Idiyappam","🍜","idiyappam",95,2,0,"string hopper"),
 F("Poori","🫓","poori",130,2.5,0,"puri"),
 F("Medhu vada","🍩","vada",140,3,0,"vada garelu"),
 F("Chapati","🫓","chapati",100,3.5,0,"roti"),
 F("Phulka","🫓","phulka",70,3,0,"roti chapati"),
 F("Paratha (plain)","🫓","paratha",210,5),
 F("Naan","🫓","naan",260,8),
 F("Bread slice","🍞","slice",70,2.5),
 /* rice dishes */
 F("White rice (cooked)","🍚","cup",200,4,0,"annam plain"),
 F("Brown rice (cooked)","🍚","cup",215,5),
 F("Curd rice","🍚","cup",250,7,0,"daddojanam"),
 F("Lemon rice","🍚","cup",280,5,0,"chitranna"),
 F("Pulihora","🍚","cup",300,5,0,"tamarind rice"),
 F("Sambar rice","🍲","cup",300,9),
 F("Bisi bele bath","🍲","cup",320,9),
 F("Upma","🥣","cup",220,5),
 F("Pongal","🥣","cup",280,8),
 F("Poha","🥣","cup",200,4,0,"atukulu"),
 F("Oats (cooked in water)","🥣","cup",160,6),
 F("Ragi malt","🥤","cup",180,5,0,"java ambali"),
 /* curries, dals, sides */
 F("Sambar","🥣","cup",120,6),
 F("Rasam","🍲","cup",60,2,0,"charu"),
 F("Dal (toor)","🫘","katori",140,8,0,"pappu"),
 F("Coconut chutney","🥥","2 tbsp",90,2),
 F("Tomato chutney","🍅","2 tbsp",50,1,0,"pachadi"),
 F("Ginger chutney","🌶️","2 tbsp",60,1,0,"allam"),
 F("Curd","🥛","cup",100,6,0,"yogurt perugu dahi"),
 F("Buttermilk","🥛","glass",60,3,0,"majjiga chaas"),
 F("Avial","🥥","cup",160,4),
 F("Gutti vankaya","🍆","serving",190,4,0,"stuffed brinjal"),
 F("Veg poriyal / fry","🥬","serving",90,3,0,"vepudu curry"),
 F("Cabbage fry","🥬","serving",85,3),
 F("Beans poriyal","🥬","serving",80,3),
 F("Beetroot poriyal","🥬","serving",90,3),
 F("Sautéed vegetables","🥦","serving",90,3),
 F("Mixed veg curry","🥘","cup",180,5),
 F("Palak paneer","🥬","cup",280,14),
 F("Paneer curry","🧀","cup",320,16),
 F("Paneer (raw)","🧀","g",265,18,1),
 F("Chana masala","🫘","cup",270,12,0,"chole"),
 F("Rajma","🫘","cup",240,12),
 F("Sprouts salad","🥗","cup",120,8,0,"moong"),
 F("Kachumber salad","🥗","serving",60,2,0,"onion tomato"),
 F("Papad","🫓","papad",40,2,0,"appadam"),
 F("Pickle","🥫","tsp",30,0,0,"avakaya"),
 /* meat, fish, egg */
 F("Chicken breast (cooked)","🍗","g",165,31,1,"grilled"),
 F("Chicken curry","🍗","g",200,25,1,"kodi kura"),
 F("Chicken tikka","🍗","g",187,27,1),
 F("Chicken 65","🍗","g",227,20,1),
 F("Chicken pepper fry","🍗","g",200,25,1,"vepudu"),
 F("Tandoori chicken","🍗","g",175,28,1),
 F("Fish curry","🐟","g",167,21,1,"chepala pulusu"),
 F("Fish fry","🐟","g",180,22,1,"chepa vepudu"),
 F("Grilled fish","🐟","g",167,22,1),
 F("Prawn curry","🦐","g",145,21,1,"shrimp royyalu"),
 F("Grilled shrimp","🦐","g",167,22,1,"prawn"),
 F("Shrimp stir fry","🦐","g",144,21,1,"prawn royyalu"),
 F("Goat curry","🍛","g",275,23,1,"mutton"),
 F("Mutton fry","🍛","g",290,25,1,"goat"),
 F("Boiled egg","🥚","egg",70,6,0,"anda kodi guddu"),
 F("Egg white (boiled)","🥚","white",17,3.5),
 F("Omelette","🍳","egg",95,7),
 F("Egg curry","🍛","egg",110,7,0,"kodi guddu"),
 F("Egg bhurji","🍳","egg",115,7,0,"scrambled"),
 /* full meals */
 F("Chicken biryani","🍛","plate",700,35),
 F("Mutton biryani","🍛","plate",800,38,0,"goat"),
 F("Veg biryani","🍛","plate",600,14),
 F("Egg biryani","🍛","plate",650,24),
 F("Veg fried rice","🍚","plate",500,10),
 F("Chicken fried rice","🍚","plate",600,25),
 F("Noodles","🍜","plate",450,12,0,"hakka chowmein"),
 F("Shawarma","🌯","roll",500,30),
 F("Burger","🍔","burger",550,25),
 F("Pizza","🍕","slice",285,12),
 F("Veg sandwich","🥪","sandwich",300,9),
 F("Meals plate (veg thali)","🍽️","plate",750,20,0,"thali"),
 /* drinks */
 F("Black coffee","☕","cup",5,0,0,"no sugar"),
 F("Filter coffee","☕","cup",110,3,0,"with milk sugar"),
 F("Tea with sugar","☕","cup",90,2,0,"chai"),
 F("Green tea","🍵","cup",2,0),
 F("Milk (full fat)","🥛","glass",150,8),
 F("Milk (toned)","🥛","glass",110,8),
 F("Whey shake","🥤","scoop",120,24,0,"protein powder"),
 F("Protein shake with milk","🥤","glass",270,32),
 F("Soft drink","🥤","can",140,0,0,"coke pepsi soda"),
 F("Sweet lime soda","🥤","glass",100,0),
 F("Salt lime soda","🥤","glass",20,0),
 F("Sweet lassi","🥛","glass",220,7),
 F("Coconut water","🥥","glass",45,1),
 F("Orange juice","🧃","glass",110,2),
 F("Beer","🍺","bottle",150,1),
 F("Whisky (30 ml peg)","🥃","peg",70,0,0,"rum vodka"),
 F("Wine","🍷","glass",125,0),
 /* fruit & nuts */
 F("Banana","🍌","banana",105,1,0,"arati"),
 F("Apple","🍎","apple",95,0.5),
 F("Orange","🍊","orange",62,1),
 F("Mango","🥭","mango",200,3),
 F("Papaya","🍈","cup",60,1),
 F("Watermelon","🍉","cup",46,1),
 F("Grapes","🍇","cup",100,1),
 F("Guava","🍐","guava",68,2.5,0,"jama"),
 F("Fruit bowl","🍉","bowl",120,2),
 F("Almonds","🌰","almond",7,0.26,0,"badam"),
 F("Peanuts (roasted)","🥜","g",567,26,1,"palli groundnut"),
 F("Roasted chana","🥜","g",400,23,1,"senagalu"),
 F("Cashews","🥜","g",553,18,1,"jeedipappu"),
 F("Walnuts","🌰","g",654,15,1,"akhrot"),
 F("Dates","🌴","date",20,0.2,0,"khajur"),
 /* snacks & sweets */
 F("Samosa","🥟","samosa",250,4),
 F("Mirchi bajji","🌶️","bajji",180,3,0,"punugulu pakoda"),
 F("Punugulu","🍩","piece",60,1),
 F("Murukku","🥨","piece",90,1.5,0,"chakli"),
 F("Marie biscuit","🍪","biscuit",25,0.4),
 F("Cream biscuit","🍪","biscuit",55,0.7),
 F("Gulab jamun","🍮","piece",150,2),
 F("Laddu","🍡","laddu",190,3),
 F("Ice cream","🍨","scoop",210,4),
 F("Chocolate bar","🍫","bar",230,3),
 F("Chips packet (small)","🥔","packet",170,2),
 F("Cake","🍰","slice",350,4),
 F("Payasam","🍮","cup",250,5,0,"kheer"),
 F("Halwa","🍮","serving",280,3),
 /* fats & extras */
 F("Ghee","🧈","tsp",45,0,0,"neyyi"),
 F("Cooking oil","🫒","tsp",40,0),
 F("Butter","🧈","tsp",34,0),
 F("Sugar","🍬","tsp",16,0),
 F("Honey","🍯","tsp",21,0),
 /* ===== Telugu vegetable curries, pappus and pachadis ===== */
 F("Vankaya kura","🍆","serving",150,3,0,"brinjal eggplant curry"),
 F("Bendakaya vepudu","🥬","serving",160,3,0,"okra bhindi fry"),
 F("Beerakaya kura","🥒","serving",110,3,0,"ridge gourd"),
 F("Sorakaya kura","🥒","serving",100,2,0,"bottle gourd lauki"),
 F("Dondakaya vepudu","🥬","serving",140,3,0,"ivy gourd tindora"),
 F("Kakarakaya vepudu","🥬","serving",150,3,0,"bitter gourd karela"),
 F("Aloo kura","🥔","serving",190,4,0,"potato bangaladumpa"),
 F("Cabbage kura","🥬","serving",90,3,0),
 F("Thotakura fry","🥬","serving",110,4,0,"amaranth leaves"),
 F("Menthi kura","🌿","serving",120,4,0,"methi fenugreek"),
 F("Bachali kura","🌿","serving",120,3,0,"malabar spinach"),
 F("Chukkakura pappu","🌿","katori",160,9,0,"sorrel dal"),
 F("Chamadumpa fry","🥔","serving",180,3,0,"colocasia arbi"),
 F("Kandagadda kura","🥔","serving",160,3,0,"yam elephant foot"),
 F("Aratikaya vepudu","🍌","serving",150,3,0,"raw banana plantain"),
 F("Munakkaya charu","🌿","cup",90,3,0,"drumstick stew"),
 F("Dosakaya kura","🥒","serving",100,2,0,"yellow cucumber"),
 F("Mudda pappu","🫘","katori",150,9,0,"plain dal ghee"),
 F("Tomato pappu","🍅","katori",150,8,0,"tomato dal"),
 F("Palakura pappu","🥬","katori",160,9,0,"spinach palak dal"),
 F("Dosakaya pappu","🥒","katori",150,8,0,"cucumber dal"),
 F("Mamidikaya pappu","🥭","katori",160,8,0,"raw mango dal"),
 F("Chintakaya pappu","🫘","katori",160,8,0,"tamarind dal"),
 F("Sorakaya pappu","🥒","katori",150,8,0,"bottle gourd dal"),
 F("Ulava charu","🫘","cup",140,7,0,"horse gram broth"),
 F("Pachi pulusu","🍅","cup",70,1,0,"raw tamarind"),
 F("Majjiga pulusu","🥛","cup",120,4,0,"buttermilk stew"),
 F("Pulusu","🍲","cup",120,3,0,"tamarind stew"),
 F("Gongura pachadi","🌿","2 tbsp",70,1,0,"sorrel chutney"),
 F("Vankaya pachadi","🍆","2 tbsp",70,1,0,"brinjal chutney"),
 F("Beerakaya pachadi","🥒","2 tbsp",60,1,0,"ridge gourd chutney"),
 F("Tomato pachadi","🍅","2 tbsp",60,1,0),
 F("Peanut chutney","🥜","2 tbsp",110,4,0,"palli chutney"),
 F("Kandi pachadi","🫘","2 tbsp",90,5,0,"toor dal chutney"),
 F("Karam podi","🌶️","tbsp",60,3,0,"idli podi gunpowder"),
 F("Avakaya","🥭","tsp",35,0,0,"mango pickle"),

 /* ===== Telugu non-veg ===== */
 F("Kodi vepudu","🍗","g",210,26,1,"chicken fry"),
 F("Kodi pulusu","🍗","g",180,24,1,"chicken tamarind curry"),
 F("Natu kodi pulusu","🍗","g",180,25,1,"country chicken"),
 F("Chepa pulusu","🐟","g",160,20,1,"fish tamarind curry"),
 F("Chepa vepudu","🐟","g",185,22,1,"fish fry"),
 F("Royyala iguru","🦐","g",160,21,1,"prawn dry curry"),
 F("Royyala vepudu","🦐","g",175,22,1,"prawn fry"),
 F("Gongura mutton","🍛","g",280,24,1,"sorrel goat"),
 F("Mutton pulusu","🍛","g",260,23,1,"goat tamarind curry"),
 F("Boti curry","🍛","g",220,20,1,"offal intestine"),
 F("Egg pulusu","🍛","egg",120,7,0,"kodi guddu"),
 F("Chicken pakoda","🍗","g",270,22,1),

 /* ===== Boiled and steamed ===== */
 F("Boiled chickpeas","🫘","cup",270,15,0,"senagalu chana kabuli"),
 F("Boiled black chana","🫘","cup",270,15,0,"kala nalla senagalu"),
 F("Guggillu","🫘","cup",250,14,0,"boiled chana snack"),
 F("Sundal","🫘","cup",240,12,0,"boiled legume snack"),
 F("Boiled peanuts","🥜","cup",200,12,0,"ubbetti palli"),
 F("Boiled corn","🌽","cob",120,4,0,"mokkajonna"),
 F("Boiled sweet potato","🍠","cup",180,4,0,"chilagadadumpa"),
 F("Boiled tapioca","🥔","cup",190,2,0,"karrapendalam"),
 F("Sprouted moong","🌱","cup",120,8,0,"pesalu sprouts"),
 F("Boiled green peas","🫛","cup",130,8,0,"batani"),
 F("Steamed beetroot","🥬","cup",75,2,0),

 /* ===== Tiffins and millets ===== */
 F("Minapattu","🫓","attu",170,5,0,"urad dosa"),
 F("Set dosa","🫓","dosa",120,3,0),
 F("Neer dosa","🫓","dosa",90,2,0),
 F("Onion dosa","🫓","dosa",200,4,0,"ullipaya"),
 F("Karam dosa","🫓","dosa",190,4,0,"spicy"),
 F("Ghee karam dosa","🫓","dosa",260,4,0),
 F("Rava idli","🍚","idli",90,3,0),
 F("Garelu","🍩","vada",140,3,0,"medu vada"),
 F("Sambar vada","🍩","vada",200,5,0),
 F("Perugu garelu","🍩","vada",180,5,0,"dahi vada"),
 F("Masala vada","🍩","vada",160,6,0,"chana dal vada"),
 F("Pesara punugulu","🍩","piece",70,2,0),
 F("Idli with karam podi","🍚","idli",95,3,0,"ghee podi"),
 F("Ragi mudda","🟤","ball",250,6,0,"ragi sangati"),
 F("Jonna sangati","🟤","ball",240,6,0,"sorghum"),
 F("Jonna roti","🫓","roti",110,3,0,"jowar"),
 F("Sajja roti","🫓","roti",120,3,0,"bajra pearl millet"),
 F("Akki roti","🫓","roti",150,3,0,"rice roti"),
 F("Puttu","🍚","cup",210,4,0),
 F("Kadala curry","🫘","cup",250,12,0,"black chana kerala"),
 F("Parotta","🫓","parotta",300,6,0,"kerala"),

 /* ===== Rice plates ===== */
 F("Muddapappu annam","🍚","plate",420,14,0,"dal rice ghee"),
 F("Ghee rice","🍚","cup",280,5,0,"nei choru"),
 F("Veg pulao","🍚","cup",270,6,0),
 F("Kodi pulao","🍚","plate",600,28,0,"chicken pulao"),
 F("Gongura rice","🍚","cup",300,5,0),
 F("Coconut rice","🥥","cup",300,5,0,"kobbari annam"),
 F("Ulava charu biryani","🍛","plate",700,25,0),

 /* ===== Tamil, Kerala, Karnataka ===== */
 F("Kootu","🥬","cup",160,6,0),
 F("Paruppu usili","🫘","serving",180,9,0),
 F("Vatha kuzhambu","🍲","cup",130,3,0),
 F("Mor kuzhambu","🥛","cup",140,4,0),
 F("Thoran","🥥","serving",110,3,0),
 F("Olan","🥥","cup",150,3,0),
 F("Erissery","🥥","cup",190,5,0),
 F("Meen curry","🐟","g",165,20,1,"kerala fish"),
 F("Fish molee","🐟","g",180,20,1),
 F("Beef fry","🥩","g",290,26,1,"kerala"),
 F("Kesari bath","🍮","cup",320,4,0,"rava kesari"),

 /* ===== Snacks ===== */
 F("Aloo bajji","🥔","bajji",140,2,0),
 F("Onion pakoda","🧅","serving",190,4,0,"ullipaya pakodi"),
 F("Masala peanuts","🥜","serving",220,9,0),
 F("Mixture","🥜","serving",250,6,0,"namkeen"),
 F("Chekkalu","🫓","piece",70,1,0),
 F("Sakinalu","🥨","piece",80,1,0),
 F("Veg puff","🥟","puff",250,4,0),
 F("Egg puff","🥟","puff",280,8,0),
 F("Mirchi ka salan","🌶️","cup",200,4,0),

 /* ===== Sweets ===== */
 F("Ariselu","🍡","piece",180,2,0),
 F("Bobbatlu","🫓","piece",230,4,0,"puran poli"),
 F("Poornam boorelu","🍩","piece",200,3,0),
 F("Sunnundalu","🍡","laddu",170,4,0,"urad laddu"),
 F("Pootharekulu","🍬","piece",120,1,0),
 F("Kaja","🍯","piece",210,2,0,"madatha"),
 F("Mysore pak","🍮","piece",250,2,0),
 F("Double ka meetha","🍮","serving",320,6,0),
 F("Qubani ka meetha","🍮","serving",250,2,0),
 F("Jangri","🍩","piece",150,1,0),
 F("Jalebi","🍩","piece",150,1,0),
 F("Semiya payasam","🍮","cup",240,5,0,"vermicelli kheer"),

 /* ===== Drinks ===== */
 F("Sugarcane juice","🥤","glass",180,0,0,"cheruku rasam"),
 F("Nimmakaya juice","🍋","glass",90,0,0,"lemon juice"),
 F("Badam milk","🥛","glass",220,8,0),
 F("Irani chai","☕","cup",120,3,0),
 F("Malt drink","🥛","glass",180,7,0,"horlicks boost"),

 /* ===== North Indian — dals and legumes ===== */
 F("Dal makhani","🫘","cup",290,11,0,"black urad rajma creamy"),
 F("Dal tadka","🫘","katori",170,9,0,"yellow dal fry"),
 F("Dal fry","🫘","katori",180,9,0),
 F("Chana dal","🫘","katori",180,10,0,"senagapappu"),
 F("Moong dal","🫘","katori",150,9,0,"pesarapappu"),
 F("Masoor dal","🫘","katori",160,9,0,"red lentil"),
 F("Lobia curry","🫘","cup",230,12,0,"black eyed peas bobbarlu"),
 F("Chole","🫘","cup",270,12,0,"chickpea curry punjabi"),
 F("Chole bhature","🍛","plate",700,18,0),
 F("Rajma chawal","🍛","plate",560,18,0,"kidney bean rice"),
 F("Kadhi pakora","🥛","cup",230,7,0,"besan yoghurt"),
 F("Soya chunks curry","🫘","cup",250,25,0,"meal maker"),

 /* ===== North Indian — paneer and vegetables ===== */
 F("Paneer butter masala","🧀","cup",380,16,0,"makhani"),
 F("Shahi paneer","🧀","cup",360,16,0),
 F("Matar paneer","🧀","cup",300,15,0,"peas paneer"),
 F("Kadai paneer","🧀","cup",320,16,0),
 F("Paneer tikka","🧀","g",220,20,1),
 F("Malai kofta","🧀","cup",400,10,0),
 F("Aloo gobi","🥔","serving",180,4,0,"cauliflower potato"),
 F("Aloo matar","🥔","serving",190,6,0),
 F("Jeera aloo","🥔","serving",170,3,0,"cumin potato"),
 F("Baingan bharta","🍆","cup",190,4,0,"smoked brinjal"),
 F("Bhindi masala","🥬","serving",170,3,0,"okra"),
 F("Dum aloo","🥔","cup",260,5,0),
 F("Mixed veg (North)","🥘","cup",200,5,0,"sabzi"),
 F("Sarson ka saag","🌿","cup",210,7,0,"mustard greens"),

 /* ===== North Indian — meat ===== */
 F("Butter chicken","🍗","g",210,22,1,"murgh makhani"),
 F("Chicken tikka masala","🍗","g",195,23,1),
 F("Kadai chicken","🍗","g",190,24,1),
 F("Chicken korma","🍗","g",220,22,1),
 F("Rogan josh","🍛","g",250,23,1,"mutton kashmiri"),
 F("Mutton keema","🍛","g",260,24,1,"minced goat"),
 F("Fish tikka","🐟","g",175,23,1),
 F("Chicken seekh kebab","🍢","kebab",120,11,0),

 /* ===== North Indian — breads and rice ===== */
 F("Butter naan","🫓","naan",300,8,0),
 F("Garlic naan","🫓","naan",310,8,0),
 F("Tandoori roti","🫓","roti",130,4,0),
 F("Lachha paratha","🫓","paratha",290,6,0),
 F("Aloo paratha","🫓","paratha",330,7,0),
 F("Paneer paratha","🫓","paratha",360,12,0),
 F("Missi roti","🫓","roti",180,6,0),
 F("Bhatura","🫓","bhatura",270,5,0),
 F("Kulcha","🫓","kulcha",240,6,0),
 F("Jeera rice","🍚","cup",240,4,0,"cumin rice"),

 /* ===== Street food and chaat ===== */
 F("Pav bhaji","🍛","plate",600,12,0),
 F("Vada pav","🍔","piece",290,6,0),
 F("Aloo tikki","🥔","tikki",150,3,0),
 F("Pani puri","🥟","6 pieces",180,4,0,"golgappa puchka"),
 F("Bhel puri","🥗","plate",250,6,0),
 F("Sev puri","🥗","plate",280,6,0),
 F("Dahi puri","🥗","plate",300,7,0),
 F("Papdi chaat","🥗","plate",320,7,0),
 F("Veg momos","🥟","6 pieces",240,7,0,"dumpling"),
 F("Chicken momos","🥟","6 pieces",300,16,0),
 F("Spring roll","🥟","roll",190,4,0),

 /* ===== Accompaniments ===== */
 F("Boondi raita","🥛","cup",150,5,0),
 F("Cucumber raita","🥛","cup",90,4,0),
 F("Green chutney","🌿","2 tbsp",40,1,0,"mint coriander"),
 F("Onion salad","🧅","serving",45,1,0,"laccha"),

 /* ===== North Indian sweets and drinks ===== */
 F("Rasgulla","🍮","piece",125,3,0),
 F("Rasmalai","🍮","piece",190,5,0),
 F("Gajar ka halwa","🍮","serving",320,5,0,"carrot halwa"),
 F("Kaju barfi","🍬","piece",130,2,0),
 F("Soan papdi","🍬","piece",110,1,0),
 F("Kulfi","🍨","piece",200,4,0),
 F("Salted lassi","🥛","glass",110,6,0,"namkeen chaas"),
 F("Masala chai","☕","cup",100,2,0),
 F("Thandai","🥛","glass",230,7,0),

 /* ===== Dry fruit, nut and seed packs — the healthy evening snack =====
    Pack rows are the ~30 g single-serve size (Sam's Club / Costco style).
    Loose nuts stay per 100 g so you can weigh a bigger handful. */
 F("Trail mix pack","🥜","pack",140,4,0,"dry fruit nuts seeds raisins sams costco"),
 F("Mixed dry fruits pack","🥜","pack",150,4,0,"dryfruit nuts sams costco"),
 F("Mixed nuts and seeds","🥜","g",570,18,1,"dry fruit"),
 F("Almond pack","🌰","pack",170,6,0,"badam 30g dry fruit"),
 F("Cashew pack","🥜","pack",165,5,0,"jeedipappu dry fruit"),
 F("Walnut pack","🌰","pack",195,5,0,"akhrot dry fruit"),
 F("Pistachios","🥜","g",560,20,1,"pista dry fruit"),
 F("Raisins","🍇","g",299,3,1,"kishmish dry fruit"),
 F("Dried figs","🟤","fig",30,0.4,0,"anjeer dry fruit"),
 F("Dried apricots","🍑","piece",17,0.2,0,"khubani dry fruit"),
 F("Prunes","🟣","piece",23,0.2,0,"dried plum dry fruit"),
 F("Dried cranberries","🔴","g",308,0.1,1,"dry fruit"),
 F("Pumpkin seeds","🎃","g",559,30,1,"seeds"),
 F("Sunflower seeds","🌻","g",584,21,1,"seeds"),
 F("Chia seeds","⚫","tbsp",60,2,0,"seeds"),
 F("Flax seeds","🟤","tbsp",55,2,0,"avise ginjalu seeds"),
 F("Makhana","🍿","cup",100,3,0,"roasted fox nuts phool"),
 F("Peanut butter","🥜","tbsp",95,4,0),
 F("Granola bar","🍫","bar",190,4,0,"cereal bar"),
 F("Protein bar","🍫","bar",220,20,0),
 F("Rice, raw (uncooked)","🍚","g",360,7,1,"biyyam before cooking dry"),
 F("Rice, 1 measuring cup raw","🍚","cup",650,12,0,"200ml glass biyyam uncooked dry"),
 F("Rice, raw (basmati)","🍚","g",350,8,1,"uncooked dry"),
 F("Rice + quinoa (cooked)","🍚","cup",215,6,0,"half and half mix standard annam"),
 F("Quinoa (cooked)","🍚","cup",222,8,0),
 F("Quinoa, raw (uncooked)","🍚","g",368,14,1,"dry before cooking"),

 /* ===== Tofu and paneer ===== */
 F("Tofu, air fried","🧈","g",190,22,1,"crispy firm cubes airfryer"),
 F("Tofu, firm (raw)","🧈","g",144,17,1,"block uncooked"),
 F("Tofu, silken","🧈","g",55,5,1,"soft"),
 F("Tofu curry","🧈","cup",250,18,0,"gravy"),
 F("Tofu scramble","🍳","cup",220,20,0,"bhurji"),
 F("Paneer, air fried","🧀","g",290,20,1,"grilled cubes airfryer tikka no gravy"),
 F("Paneer bhurji","🧀","cup",300,18,0,"scrambled"),
 F("Soya chunks, dry","🫘","g",345,52,1,"meal maker nutrela uncooked"),

 /* ===== Greek yogurt and the high-protein dairy ===== */
 F("Greek yogurt (plain, nonfat)","🥛","g",59,10,1,"hung curd high protein"),
 F("Greek yogurt, 1 cup plain","🥛","cup",145,25,0,"nonfat high protein"),
 F("Greek yogurt (full fat)","🥛","g",97,9,1,"plain"),
 F("Greek yogurt (flavoured)","🥛","cup",190,18,0,"fruit sweetened"),
 F("Skyr","🥛","cup",140,25,0,"icelandic high protein"),
 F("Cottage cheese","🧀","g",98,11,1,"low fat"),
 F("Hung curd","🥛","cup",180,14,0,"chakka strained yoghurt"),

 /* ===== Protein powders — whey is one of these, not a different thing ===== */
 F("Whey protein powder","🥤","scoop",120,24,0,"concentrate shake supplement"),
 F("Whey isolate","🥤","scoop",110,25,0,"protein powder supplement"),
 F("Casein protein","🥤","scoop",120,24,0,"protein powder slow overnight"),
 F("Plant protein powder","🥤","scoop",120,21,0,"pea soy vegan supplement"),
 F("Mass gainer","🥤","scoop",380,20,0,"protein powder bulk"),
 F("Protein shake with water","🥤","glass",120,24,0,"whey powder"),
 F("Protein shake with Greek yogurt","🥤","glass",290,45,0,"whey powder"),

 /* ===================================================================
    Eating out in the USA. Figures are the published ones rounded off;
    portions vary by location, so treat them as close, not exact.
    =================================================================== */

 /* --- Chipotle, Cava, Sweetgreen style bowls --- */
 F("Chipotle bowl, chicken","🥙","bowl",630,45,0,"burrito rice beans salsa"),
 F("Chipotle bowl, steak","🥙","bowl",650,40,0,"burrito"),
 F("Chipotle bowl, barbacoa","🥙","bowl",640,40,0,"burrito"),
 F("Chipotle bowl, carnitas","🥙","bowl",670,37,0,"burrito"),
 F("Chipotle bowl, sofritas","🥙","bowl",550,20,0,"burrito tofu veg"),
 F("Chipotle salad bowl, no rice","🥗","bowl",400,40,0,"chicken low carb"),
 F("Chipotle burrito, chicken","🌯","burrito",1000,50,0,"wrap"),
 F("Chipotle chips","🌮","bag",540,7,0),
 F("Guacamole side","🥑","side",230,2,0,"chipotle"),
 F("Cava bowl, chicken","🥙","bowl",700,45,0,"mediterranean grain"),
 F("Cava bowl, falafel","🥙","bowl",650,20,0,"mediterranean"),
 F("Cava bowl, harissa avocado","🥙","bowl",700,35,0,"mediterranean"),
 F("Cava greens and grains","🥗","bowl",600,30,0,"mediterranean"),
 F("Sweetgreen salad, chicken","🥗","bowl",520,32,0,"greens"),
 F("Poke bowl","🍣","bowl",600,35,0,"hawaiian salmon tuna"),
 F("Acai bowl","🍇","bowl",550,8,0,"smoothie granola"),

 /* --- McDonald's --- */
 F("Big Mac","🍔","burger",590,25,0,"mcdonalds mcd"),
 F("Quarter Pounder with cheese","🍔","burger",520,30,0,"mcdonalds mcd"),
 F("McDouble","🍔","burger",400,22,0,"mcdonalds mcd"),
 F("McChicken","🍔","sandwich",400,14,0,"mcdonalds mcd"),
 F("Filet-O-Fish","🍔","sandwich",390,15,0,"mcdonalds mcd"),
 F("Chicken McNuggets, 10 pc","🍗","serving",410,23,0,"mcdonalds mcd"),
 F("Chicken McNuggets, 6 pc","🍗","serving",250,14,0,"mcdonalds mcd"),
 F("McDonald's fries, medium","🍟","serving",320,5,0,"mcd"),
 F("McDonald's fries, large","🍟","serving",480,7,0,"mcd"),
 F("Egg McMuffin","🥪","sandwich",310,17,0,"mcdonalds mcd breakfast"),
 F("Sausage McMuffin with egg","🥪","sandwich",480,20,0,"mcdonalds mcd breakfast"),
 F("Hash brown","🥔","piece",140,2,0,"mcdonalds mcd breakfast"),
 F("McFlurry, Oreo","🍦","serving",510,12,0,"mcdonalds mcd dessert"),

 /* --- Chick-fil-A --- */
 F("Chick-fil-A sandwich","🍔","sandwich",440,28,0,"chicken cfa"),
 F("Chick-fil-A spicy sandwich","🍔","sandwich",450,28,0,"chicken cfa"),
 F("Chick-fil-A grilled sandwich","🍔","sandwich",390,28,0,"chicken cfa"),
 F("Chick-fil-A nuggets, 8 pc","🍗","serving",250,27,0,"cfa"),
 F("Chick-fil-A nuggets, 12 pc","🍗","serving",380,40,0,"cfa"),
 F("Chick-fil-A grilled nuggets, 8 pc","🍗","serving",130,25,0,"cfa"),
 F("Waffle fries, medium","🍟","serving",420,5,0,"chick-fil-a cfa"),
 F("Chick-fil-A cobb salad","🥗","salad",510,40,0,"cfa"),
 F("Chick-fil-A wrap","🌯","wrap",660,37,0,"cfa cool"),
 F("Chick-fil-A sauce","🥫","packet",140,0,0,"cfa"),
 F("Chick-fil-A lemonade, medium","🥤","glass",220,0,0,"cfa"),

 /* --- other American chains --- */
 F("Subway 6 inch turkey","🥪","sandwich",280,18,0,"sub"),
 F("Subway 6 inch chicken teriyaki","🥪","sandwich",370,26,0,"sub"),
 F("Subway footlong steak and cheese","🥪","sandwich",760,48,0,"sub"),
 F("Five Guys hamburger","🍔","burger",700,39,0),
 F("In-N-Out Double-Double","🍔","burger",670,37,0),
 F("Shake Shack ShackBurger","🍔","burger",530,29,0),
 F("Wendy's Dave's Single","🍔","burger",570,29,0),
 F("Popeyes chicken sandwich","🍔","sandwich",700,28,0),
 F("KFC chicken tenders, 3 pc","🍗","serving",380,40,0),
 F("Pizza slice, pepperoni","🍕","slice",300,13,0,"dominos papa johns"),
 F("Pizza slice, cheese","🍕","slice",270,12,0,"dominos"),
 F("Buffalo wings, 6 pc","🍗","serving",660,42,0,"hot wings"),
 F("Panera broccoli cheddar bread bowl","🥣","bowl",900,25,0,"soup"),
 F("Hot dog","🌭","hot dog",300,12,0,"ballpark"),
 F("Philly cheesesteak","🥪","sandwich",800,45,0),
 F("BBQ pulled pork sandwich","🥪","sandwich",600,30,0),

 /* --- tacos and Mexican --- */
 F("Street taco, carne asada","🌮","taco",200,12,0,"mexican beef"),
 F("Street taco, al pastor","🌮","taco",210,12,0,"mexican pork"),
 F("Street taco, chicken","🌮","taco",180,12,0,"mexican pollo"),
 F("Street taco, carnitas","🌮","taco",220,13,0,"mexican pork"),
 F("Birria taco","🌮","taco",300,15,0,"mexican quesabirria"),
 F("Fish taco","🌮","taco",250,13,0,"mexican baja"),
 F("Taco Bell crunchy taco","🌮","taco",170,8,0,"mexican"),
 F("Taco Bell Crunchwrap Supreme","🌯","wrap",530,16,0,"mexican"),
 F("Taco Bell bean burrito","🌯","burrito",350,13,0,"mexican"),
 F("Burrito, chicken","🌯","burrito",900,45,0,"mexican"),
 F("Burrito, beef","🌯","burrito",950,40,0,"mexican"),
 F("Quesadilla, chicken","🫓","quesadilla",700,40,0,"mexican"),
 F("Nachos with cheese","🌮","plate",800,20,0,"mexican"),
 F("Chips and salsa","🌮","serving",300,5,0,"mexican"),
 F("Chips and guacamole","🥑","serving",500,6,0,"mexican"),
 F("Enchiladas, 2","🌮","serving",600,25,0,"mexican"),
 F("Chicken fajitas plate","🌯","plate",700,45,0,"mexican"),
 F("Elote","🌽","cob",200,5,0,"mexican street corn"),
 F("Rice and beans side","🍚","serving",350,12,0,"mexican"),
 F("Horchata","🥛","glass",250,3,0,"mexican"),

 /* --- Thai --- */
 F("Pad thai, chicken","🍜","plate",900,35,0,"thai noodles"),
 F("Pad see ew","🍜","plate",850,30,0,"thai noodles"),
 F("Drunken noodles","🍜","plate",850,30,0,"thai pad kee mao"),
 F("Thai green curry with rice","🍛","plate",700,25,0,"thai"),
 F("Thai red curry with rice","🍛","plate",700,25,0,"thai"),
 F("Massaman curry with rice","🍛","plate",750,25,0,"thai"),
 F("Panang curry with rice","🍛","plate",730,26,0,"thai"),
 F("Thai basil chicken with rice","🍛","plate",750,35,0,"thai pad krapow"),
 F("Thai fried rice","🍚","plate",750,25,0,"thai"),
 F("Tom yum soup","🍲","bowl",150,12,0,"thai"),
 F("Tom kha gai","🍲","bowl",250,12,0,"thai coconut soup"),
 F("Som tum papaya salad","🥗","plate",150,4,0,"thai"),
 F("Chicken satay, 4 skewers","🍢","serving",300,30,0,"thai"),
 F("Thai spring rolls, 2","🥟","serving",200,5,0,"thai"),
 F("Mango sticky rice","🍮","serving",450,6,0,"thai dessert"),

 /* --- Mediterranean and Middle Eastern --- */
 F("Chicken shawarma plate","🍽️","plate",800,50,0,"mediterranean halal"),
 F("Chicken over rice","🍚","plate",900,45,0,"halal cart mediterranean"),
 F("Lamb gyro","🌯","gyro",700,35,0,"greek mediterranean"),
 F("Chicken souvlaki plate","🍢","plate",650,50,0,"greek mediterranean"),
 F("Beef kebab plate","🍢","plate",750,45,0,"mediterranean"),
 F("Falafel wrap","🌯","wrap",600,18,0,"mediterranean"),
 F("Falafel, 4 pieces","🧆","serving",300,12,0,"mediterranean"),
 F("Greek salad","🥗","salad",300,8,0,"mediterranean feta"),
 F("Hummus","🥣","2 tbsp",70,2,0,"mediterranean"),
 F("Baba ganoush","🍆","2 tbsp",60,1,0,"mediterranean"),
 F("Tzatziki","🥛","2 tbsp",40,2,0,"greek mediterranean"),
 F("Tabbouleh","🥗","serving",120,3,0,"mediterranean"),
 F("Pita bread","🫓","pita",165,5,0,"mediterranean"),
 F("Baklava","🍯","piece",200,3,0,"mediterranean dessert"),

 /* --- American plates and diner --- */
 F("Grilled chicken breast plate","🍗","plate",400,50,0,"american"),
 F("Sirloin steak, 8 oz","🥩","plate",500,60,0,"american"),
 F("Salmon fillet, 6 oz","🐟","fillet",350,40,0,"american grilled"),
 F("Caesar salad with chicken","🥗","salad",600,40,0,"american"),
 F("Cobb salad","🥗","salad",550,35,0,"american"),
 F("Chili con carne","🍲","bowl",400,25,0,"american"),
 F("Clam chowder","🍲","bowl",300,12,0,"american soup"),
 F("Mac and cheese","🧀","cup",450,16,0,"american"),
 F("Mashed potatoes","🥔","cup",240,4,0,"american"),
 F("Baked potato","🥔","potato",260,7,0,"american"),
 F("Coleslaw","🥬","serving",200,1,0,"american"),
 F("Pancakes with syrup, 3","🥞","serving",600,12,0,"american breakfast"),
 F("Waffle with butter and syrup","🧇","waffle",450,8,0,"american breakfast"),
 F("Bacon, 2 strips","🥓","serving",90,6,0,"american breakfast"),
 F("Sausage patty","🥓","patty",100,5,0,"american breakfast"),
 F("Scrambled eggs, 2","🍳","serving",200,12,0,"american breakfast"),
 F("Avocado toast","🥑","slice",350,10,0,"american breakfast"),
 F("Bagel with cream cheese","🥯","bagel",450,13,0,"american breakfast"),
 F("Protein bowl, chicken and rice","🍚","bowl",650,45,0,"american meal prep"),

 /* --- desserts --- */
 F("Cheesecake slice","🍰","slice",400,7,0,"dessert"),
 F("Brownie","🍫","piece",350,4,0,"dessert"),
 F("Chocolate chip cookie","🍪","cookie",200,2,0,"dessert"),
 F("Glazed donut","🍩","donut",250,3,0,"dessert dunkin krispy"),
 F("Cinnamon roll","🍥","roll",450,7,0,"dessert"),
 F("Apple pie slice","🥧","slice",320,3,0,"dessert"),
 F("Ice cream sundae","🍨","serving",500,8,0,"dessert"),
 F("Milkshake","🥤","glass",600,12,0,"dessert"),
 F("Frozen yogurt","🍦","cup",250,6,0,"dessert froyo"),
 F("Gelato","🍨","scoop",180,4,0,"dessert"),
 F("Tiramisu","🍰","serving",350,5,0,"dessert"),
 F("Churros, 3","🥖","serving",350,4,0,"dessert mexican"),
 F("Mochi ice cream, 2","🍡","serving",220,2,0,"dessert"),

 /* --- fruit --- */
 F("Strawberries","🍓","cup",50,1,0,"fruit berries"),
 F("Blueberries","🫐","cup",85,1,0,"fruit berries"),
 F("Raspberries","🍇","cup",65,1.5,0,"fruit berries"),
 F("Blackberries","🫐","cup",62,2,0,"fruit berries"),
 F("Pineapple","🍍","cup",82,1,0,"fruit"),
 F("Kiwi","🥝","kiwi",42,0.8,0,"fruit"),
 F("Pear","🍐","pear",100,0.6,0,"fruit"),
 F("Peach","🍑","peach",60,1.4,0,"fruit"),
 F("Plum","🟣","plum",30,0.5,0,"fruit"),
 F("Cherries","🍒","cup",90,1.5,0,"fruit"),
 F("Pomegranate seeds","🔴","cup",145,3,0,"fruit anar"),
 F("Avocado","🥑","half",160,2,0,"fruit"),
 F("Cantaloupe","🍈","cup",55,1,0,"fruit muskmelon"),
 F("Honeydew","🍈","cup",60,1,0,"fruit"),
 F("Dragon fruit","🐉","fruit",60,1.2,0,"fruit"),
 F("Lychee","🥭","cup",125,1.6,0,"fruit"),
 F("Custard apple","🟢","fruit",94,2,0,"fruit sitaphal"),
 F("Sapota","🟤","fruit",83,0.4,0,"fruit chikoo"),
 F("Jackfruit","🟡","cup",155,2.4,0,"fruit panasa"),
 F("Tangerine","🍊","fruit",47,0.7,0,"fruit clementine"),
 F("Grapefruit","🍊","half",52,1,0,"fruit"),
 F("Fresh figs","🟤","fig",37,0.4,0,"fruit anjeer"),

 /* --- American drinks --- */
 F("Latte, grande","☕","cup",190,13,0,"starbucks coffee"),
 F("Cappuccino","☕","cup",120,8,0,"starbucks coffee"),
 F("Cold brew, black","☕","cup",5,0,0,"starbucks coffee"),
 F("Iced coffee with milk","☕","cup",80,4,0,"starbucks"),
 F("Frappuccino","🥤","cup",380,5,0,"starbucks"),
 F("Boba tea","🧋","cup",350,3,0,"bubble milk tea"),
 F("Fruit smoothie","🥤","cup",300,4,0,"smoothie"),
 F("Protein smoothie","🥤","cup",400,30,0,"smoothie"),
 F("Gatorade","🥤","bottle",140,0,0,"sports drink"),
 F("Diet soda","🥤","can",0,0,0,"coke zero pepsi"),
 F("Red Bull","🥤","can",110,0,0,"energy drink"),
 F("Margarita","🍸","glass",250,0,0,"cocktail"),

 /* --- grocery staples and easy protein --- */
 F("String cheese","🧀","stick",80,7,0,"snack"),
 F("Beef jerky","🥩","oz",80,13,0,"snack"),
 F("Bottled protein shake","🥤","bottle",160,30,0,"premier fairlife"),
 F("Tuna, canned","🐟","g",130,28,1,"drained"),
 F("Rotisserie chicken","🍗","g",190,25,1,"costco"),
 F("Turkey slices","🦃","g",110,17,1,"deli"),
 F("Salmon, cooked","🐟","g",208,22,1),
 F("Egg whites, carton","🥚","g",52,11,1),
 F("Oatmeal packet","🥣","packet",150,4,0,"instant"),
 F("Peanut butter sandwich","🥪","sandwich",380,13,0,"pb"),
 F("Popcorn","🍿","3 cups",90,3,0,"snack"),
 F("Rice cake","🍘","cake",35,1,0,"snack"),
 F("Almond milk","🥛","cup",40,1,0,"unsweetened"),
 F("Oat milk","🥛","cup",120,3,0)



];
export const FAVES: string[] = ["Banana","Boiled egg","Black coffee","Tea with sugar","Curd","Rice + quinoa (cooked)","Phulka","Whey shake","Greek yogurt, 1 cup plain","Trail mix pack","Chicken curry"];

export const foodByName = (n: string) => FOODS.find((f) => f.n === n);
export const perUnit = (f: Food) => (f.g ? `${f.k} kcal / 100 g` : `${f.k} kcal per ${f.u}`);
export const defaultQty = (f: Food) => (f.g ? 150 : 1);
export const stepOf = (f: Food) => (f.g ? 25 : 1);
export const macrosFor = (f: Food, q: number) =>
  f.g ? { k: (f.k * q) / 100, p: (f.p * q) / 100 } : { k: f.k * q, p: f.p * q };

export function plural(u: string, q: number) {
  if (u === "g" || q <= 1) return u;
  if (/(s|sh|ch|x)$/.test(u)) return u + "es";
  return u + "s";
}

/** `mine` are the foods you saved your own numbers for; they rank first. */
export function findFoods(q: string, mine: Food[] = []): Food[] {
  const t = q.toLowerCase().trim().split(/\s+/).filter(Boolean);
  if (!t.length) return [];
  const seen = new Set(mine.map((f) => f.n));
  const out: { f: Food; r: number }[] = [];

  const consider = (f: Food, bonus: number) => {
    const hay = (f.n + " " + f.a).toLowerCase();
    if (t.every((x) => hay.includes(x)))
      out.push({ f, r: bonus + (f.n.toLowerCase().startsWith(t[0]) ? 0 : 100) + f.n.length });
  };

  mine.forEach((f) => consider(f, -1000));
  FOODS.forEach((f) => { if (!seen.has(f.n)) consider(f, 0); });
  return out.sort((a, b) => a.r - b.r).slice(0, 8).map((x) => x.f);
}
